version: "3.9"
services:
  app:
    image: node:16.15.1-alpine3.16
    working_dir: /app
    command: sh -c "yarn install --network-timeout=100000 && yarn dev"
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:9000:3000
